"""Geocodificación inversa: coordenadas GPS → ciudad/país (sin internet)."""
from __future__ import annotations

from functools import lru_cache
from typing import Optional

_rg = None


def _get_rg():
    global _rg
    if _rg is None:
        import reverse_geocoder as rg
        _rg = rg
    return _rg


@lru_cache(maxsize=4096)
def coords_to_city(lat: float, lon: float) -> Optional[str]:
    """
    Devuelve el nombre de la ciudad más cercana a las coordenadas dadas.
    Usa caché para no recalcular coordenadas repetidas.
    """
    try:
        rg = _get_rg()
        results = rg.search([(lat, lon)], verbose=False)
        if results:
            r = results[0]
            city = r.get("name", "").strip()
            return city if city else None
    except Exception:
        pass
    return None


# Palabras clave en nombres de carpeta → ciudades/destinos conocidos
# Añade aquí los nombres que aparezcan en tus carpetas
FOLDER_CITY_KEYWORDS: dict[str, str] = {

    # ════════════════════════════════════════════════════════════════════════
    # ESPAÑA
    # ════════════════════════════════════════════════════════════════════════

    # ── País Vasco ───────────────────────────────────────────────────────────
    "donostia":           "Donostia",
    "san sebastian":      "Donostia",
    "san sebastián":      "Donostia",
    "bilbao":             "Bilbao",
    "bilbo":              "Bilbao",
    "vitoria":            "Vitoria",
    "gasteiz":            "Vitoria",
    "getxo":              "Getxo",
    "algorta":            "Getxo",
    "portugalete":        "Portugalete",
    "santurtzi":          "Santurtzi",
    "barakaldo":          "Barakaldo",
    "sestao":             "Sestao",
    "erandio":            "Erandio",
    "leioa":              "Leioa",
    "basauri":            "Basauri",
    "galdakao":           "Galdakao",
    "durango":            "Durango",
    "hondarribia":        "Hondarribia",
    "zarautz":            "Zarautz",
    "getaria":            "Getaria",
    "zumaia":             "Zumaia",
    "mutriku":            "Mutriku",
    "lekeitio":           "Lekeitio",
    "ondarroa":           "Ondarroa",
    "bermeo":             "Bermeo",
    "mundaka":            "Mundaka",
    "guernica":           "Guernica",
    "gernika":            "Guernica",
    "irun":               "Irun",
    "renteria":           "Renteria",
    "errenteria":         "Renteria",
    "pasajes":            "Pasajes",
    "pasaia":             "Pasajes",
    "andoain":            "Andoain",
    "hernani":            "Hernani",
    "tolosa":             "Tolosa",
    "azpeitia":           "Azpeitia",
    "zumarraga":          "Zumarraga",
    "beasain":            "Beasain",
    "eibar":              "Eibar",
    "elgoibar":           "Elgoibar",
    "arrasate":           "Mondragon",
    "mondragon":          "Mondragon",
    "aretxabaleta":       "Aretxabaleta",
    "bergara":            "Bergara",
    "oñati":              "Onati",
    "onati":              "Onati",
    "azkoitia":           "Azkoitia",
    "deba":               "Deba",
    "zestoa":             "Zestoa",
    "orio":               "Orio",
    "aia":                "Aia",
    "villabona":          "Villabona",
    "irura":              "Irura",
    "lasarte":            "Lasarte",
    "usurbil":            "Usurbil",
    "anoeta":             "Anoeta",
    "urnieta":            "Urnieta",
    "astigarraga":        "Astigarraga",
    "oiartzun":           "Oiartzun",
    "lezo":               "Lezo",
    "biarritz":           "Biarritz",
    # ── Navarra ──────────────────────────────────────────────────────────────
    "pamplona":           "Pamplona",
    "iruña":              "Pamplona",
    "iruñea":             "Pamplona",
    "tudela":             "Tudela",
    "estella":            "Estella",
    "lizarra":            "Estella",
    "tafalla":            "Tafalla",
    "sangüesa":           "Sanguesa",
    "sanguesa":           "Sanguesa",
    "olite":              "Olite",
    "roncesvalles":       "Roncesvalles",
    "orreaga":            "Roncesvalles",
    "burguete":           "Burguete",
    "auritz":             "Burguete",
    # ── La Rioja ─────────────────────────────────────────────────────────────
    "logroño":            "Logrono",
    "logrono":            "Logrono",
    "calahorra":          "Calahorra",
    "haro":               "Haro",
    "nájera":             "Najera",
    "najera":             "Najera",
    "santo domingo":      "Santo_Domingo_Calzada",
    # ── Aragón ───────────────────────────────────────────────────────────────
    "zaragoza":           "Zaragoza",
    "huesca":             "Huesca",
    "teruel":             "Teruel",
    "jaca":               "Jaca",
    "benasque":           "Benasque",
    "ordesa":             "Ordesa",
    "ainsa":              "Ainsa",
    "aínsa":              "Ainsa",
    "broto":              "Broto",
    "torla":              "Torla",
    "bielsa":             "Bielsa",
    "canfranc":           "Canfranc",
    "hecho":              "Hecho",
    "ansó":               "Anso",
    "anso":               "Anso",
    "albarracin":         "Albarracin",
    "albarracín":         "Albarracin",
    "alcañiz":            "Alcaniz",
    "alcaniz":            "Alcaniz",
    # ── Cataluña ─────────────────────────────────────────────────────────────
    "barcelona":          "Barcelona",
    "girona":             "Girona",
    "gerona":             "Girona",
    "tarragona":          "Tarragona",
    "lleida":             "Lleida",
    "lerida":             "Lleida",
    "sitges":             "Sitges",
    "costa brava":        "Costa_Brava",
    "cadaques":           "Cadaques",
    "cadaqués":           "Cadaques",
    "figueres":           "Figueres",
    "empuries":           "Empuries",
    "empúries":           "Empuries",
    "l'escala":           "L_Escala",
    "escala":             "L_Escala",
    "roses":              "Roses",
    "palamos":            "Palamos",
    "palamós":            "Palamos",
    "platja d'aro":       "Platja_dAro",
    "tossa de mar":       "Tossa_de_Mar",
    "lloret de mar":      "Lloret_de_Mar",
    "blanes":             "Blanes",
    "calella":            "Calella",
    "montserrat":         "Montserrat",
    "vic":                "Vic",
    "manresa":            "Manresa",
    "igualada":           "Igualada",
    "vilafranca":         "Vilafranca",
    "reus":               "Reus",
    "delta del ebro":     "Delta_Ebro",
    "tortosa":            "Tortosa",
    "poblet":             "Poblet",
    "valls":              "Valls",
    "cambrils":           "Cambrils",
    "salou":              "Salou",
    "port aventura":      "PortAventura",
    "portaventura":       "PortAventura",
    "puigcerda":          "Puigcerda",
    "puigcerdà":          "Puigcerda",
    "berga":              "Berga",
    "ripoll":             "Ripoll",
    "olot":               "Olot",
    "banyoles":           "Banyoles",
    "begur":              "Begur",
    "tamariu":            "Tamariu",
    "calella de palafrugell": "Calella_Palafrugell",
    # ── Comunidad Valenciana ─────────────────────────────────────────────────
    "valencia":           "Valencia",
    "alicante":           "Alicante",
    "benidorm":           "Benidorm",
    "denia":              "Denia",
    "dénia":              "Denia",
    "javea":              "Javea",
    "jávea":              "Javea",
    "calpe":              "Calpe",
    "altea":              "Altea",
    "gandia":             "Gandia",
    "castellon":          "Castellon",
    "castellón":          "Castellon",
    "peniscola":          "Peniscola",
    "peñíscola":          "Peniscola",
    "vinaros":            "Vinaros",
    "vinaròs":            "Vinaros",
    "benicassim":         "Benicassim",
    "benicàssim":         "Benicassim",
    "oropesa":            "Oropesa",
    "cullera":            "Cullera",
    "xativa":             "Xativa",
    "xàtiva":             "Xativa",
    "alcoy":              "Alcoy",
    "alcoi":              "Alcoy",
    "elche":              "Elche",
    "elx":                "Elche",
    "orihuela":           "Orihuela",
    "torrevieja":         "Torrevieja",
    "santa pola":         "Santa_Pola",
    "guardamar":          "Guardamar",
    "villajoyosa":        "Villajoyosa",
    "la vila joiosa":     "Villajoyosa",
    # ── Andalucía ────────────────────────────────────────────────────────────
    "sevilla":            "Sevilla",
    "granada":            "Granada",
    "malaga":             "Malaga",
    "málaga":             "Malaga",
    "cordoba":            "Cordoba",
    "córdoba":            "Cordoba",
    "cadiz":              "Cadiz",
    "cádiz":              "Cadiz",
    "huelva":             "Huelva",
    "almeria":            "Almeria",
    "almería":            "Almeria",
    "jaen":               "Jaen",
    "jaén":               "Jaen",
    "marbella":           "Marbella",
    "torremolinos":       "Torremolinos",
    "benalmadena":        "Benalmadena",
    "benalmádena":        "Benalmadena",
    "fuengirola":         "Fuengirola",
    "nerja":              "Nerja",
    "ronda":              "Ronda",
    "jerez":              "Jerez",
    "tarifa":             "Tarifa",
    "algeciras":          "Algeciras",
    "gibraltar":          "Gibraltar",
    "antequera":          "Antequera",
    "ubeda":              "Ubeda",
    "úbeda":              "Ubeda",
    "baeza":              "Baeza",
    "guadix":             "Guadix",
    "motril":             "Motril",
    "almuñecar":          "Almunecar",
    "almunecar":          "Almunecar",
    "velez malaga":       "Velez_Malaga",
    "estepona":           "Estepona",
    "mijas":              "Mijas",
    "coin":               "Coin",
    "coín":               "Coin",
    "alhambra":           "Alhambra",
    "sierra nevada":      "Sierra_Nevada",
    "doñana":             "Donana",
    "donana":             "Donana",
    "italica":            "Italica",
    "itálica":            "Italica",
    # ── Castilla y León ──────────────────────────────────────────────────────
    "madrid":             "Madrid",
    "toledo":             "Toledo",
    "segovia":            "Segovia",
    "avila":              "Avila",
    "ávila":              "Avila",
    "salamanca":          "Salamanca",
    "valladolid":         "Valladolid",
    "burgos":             "Burgos",
    "leon":               "Leon",
    "león":               "Leon",
    "zamora":             "Zamora",
    "palencia":           "Palencia",
    "soria":              "Soria",
    "el burgo de osma":   "El_Burgo_de_Osma",
    "covarrubias":        "Covarrubias",
    "lerma":              "Lerma",
    "peñafiel":           "Penafiel",
    "penafiel":           "Penafiel",
    "aranda de duero":    "Aranda_de_Duero",
    "medina del campo":   "Medina_del_Campo",
    "tordesillas":        "Tordesillas",
    "ciudad rodrigo":     "Ciudad_Rodrigo",
    "bejar":              "Bejar",
    "béjar":              "Bejar",
    "miranda de ebro":    "Miranda_de_Ebro",
    "ponferrada":         "Ponferrada",
    "astorga":            "Astorga",
    "la bañeza":          "La_Baneza",
    # ── Castilla-La Mancha ───────────────────────────────────────────────────
    "guadalajara":        "Guadalajara",
    "cuenca":             "Cuenca",
    "ciudad real":        "Ciudad_Real",
    "albacete":           "Albacete",
    "talavera":           "Talavera",
    "sigüenza":           "Siguenza",
    "siguenza":           "Siguenza",
    "almagro":            "Almagro",
    "alarcon":            "Alarcon",
    "alarcón":            "Alarcon",
    "consuegra":          "Consuegra",
    "campo de criptana":  "Campo_de_Criptana",
    # ── Comunidad de Madrid ───────────────────────────────────────────────────
    "alcala":             "Alcala_de_Henares",
    "alcalá":             "Alcala_de_Henares",
    "aranjuez":           "Aranjuez",
    "el escorial":        "El_Escorial",
    "chinchon":           "Chinchon",
    "chinchón":           "Chinchon",
    "manzanares el real": "Manzanares_el_Real",
    "buitrago":           "Buitrago",
    # ── Galicia ──────────────────────────────────────────────────────────────
    "santiago":           "Santiago_de_Compostela",
    "compostela":         "Santiago_de_Compostela",
    "vigo":               "Vigo",
    "coruña":             "A_Coruna",
    "a coruña":           "A_Coruna",
    "pontevedra":         "Pontevedra",
    "ourense":            "Ourense",
    "lugo":               "Lugo",
    "rias bajas":         "Rias_Bajas",
    "rias baixas":        "Rias_Bajas",
    "cambados":           "Cambados",
    "baiona":             "Baiona",
    "bayona":             "Baiona",
    "tui":                "Tui",
    "redondela":          "Redondela",
    "cangas":             "Cangas",
    "moaña":              "Moana",
    "moana":              "Moana",
    "sanxenxo":           "Sanxenxo",
    "sanjenjo":           "Sanxenxo",
    "o grove":            "O_Grove",
    "el grove":           "O_Grove",
    "vilagarcia":         "Vilagarcia",
    "vilagarcía":         "Vilagarcia",
    "ribadeo":            "Ribadeo",
    "viveiro":            "Viveiro",
    "ferrol":             "Ferrol",
    "betanzos":           "Betanzos",
    "noia":               "Noia",
    "muros":              "Muros",
    "fisterra":           "Fisterra",
    "finisterre":         "Fisterra",
    "muxia":              "Muxia",
    "muxía":              "Muxia",
    "cee":                "Cee",
    "corcubion":          "Corcubion",
    "corcubión":          "Corcubion",
    "mondoñedo":          "Mondonedo",
    # ── Asturias ─────────────────────────────────────────────────────────────
    "oviedo":             "Oviedo",
    "gijon":              "Gijon",
    "gijón":              "Gijon",
    "aviles":             "Aviles",
    "avilés":             "Aviles",
    "llanes":             "Llanes",
    "ribadesella":        "Ribadesella",
    "cangas de onis":     "Cangas_de_Onis",
    "cangas de onís":     "Cangas_de_Onis",
    "covadonga":          "Covadonga",
    "picos de europa":    "Picos_de_Europa",
    "naranjo de bulnes":  "Picos_de_Europa",
    "cudillero":          "Cudillero",
    "luarca":             "Luarca",
    "tapia de casariego": "Tapia_de_Casariego",
    "villaviciosa":       "Villaviciosa",
    "lastres":            "Lastres",
    "colunga":            "Colunga",
    "navia":              "Navia",
    "castropol":          "Castropol",
    # ── Cantabria ────────────────────────────────────────────────────────────
    "santander":          "Santander",
    "comillas":           "Comillas",
    "san vicente":        "San_Vicente_Barquera",
    "san vicente de la barquera": "San_Vicente_Barquera",
    "castro urdiales":    "Castro_Urdiales",
    "laredo":             "Laredo",
    "santoña":            "Santona",
    "santona":            "Santona",
    "suances":            "Suances",
    "lierganes":          "Lierganes",
    "potes":              "Potes",
    "cabarceno":          "Cabarceno",
    "puente viesgo":      "Puente_Viesgo",
    # ── Extremadura ──────────────────────────────────────────────────────────
    "caceres":            "Caceres",
    "cáceres":            "Caceres",
    "badajoz":            "Badajoz",
    "merida":             "Merida",
    "mérida":             "Merida",
    "plasencia":          "Plasencia",
    "trujillo":           "Trujillo",
    "guadalupe":          "Guadalupe",
    "zafra":              "Zafra",
    "jerez de los caballeros": "Jerez_de_los_Caballeros",
    # ── Murcia ───────────────────────────────────────────────────────────────
    "murcia":             "Murcia",
    "cartagena":          "Cartagena",
    "lorca":              "Lorca",
    "mazarron":           "Mazarron",
    "mazarrón":           "Mazarron",
    "aguilas":            "Aguilas",
    "águilas":            "Aguilas",
    "caravaca":           "Caravaca",
    "jumilla":            "Jumilla",
    # ── Islas Baleares ───────────────────────────────────────────────────────
    "mallorca":           "Mallorca",
    "palma":              "Mallorca",
    "alcudia":            "Alcudia",
    "pollensa":           "Pollensa",
    "pollença":           "Pollensa",
    "soller":             "Soller",
    "sóller":             "Soller",
    "valldemossa":        "Valldemossa",
    "deia":               "Deia",
    "deià":               "Deia",
    "formentor":          "Formentor",
    "porto cristo":       "Porto_Cristo",
    "cala millor":        "Cala_Millor",
    "cala d'or":          "Cala_dOr",
    "ses salines":        "Ses_Salines",
    "menorca":            "Menorca",
    "mahon":              "Mahon",
    "maó":                "Mahon",
    "ciutadella":         "Ciutadella",
    "fornells":           "Fornells",
    "ibiza":              "Ibiza",
    "eivissa":            "Ibiza",
    "sant antoni":        "Sant_Antoni",
    "santa eulalia":      "Santa_Eulalia",
    "formentera":         "Formentera",
    "la savina":          "Formentera",
    # ── Islas Canarias ───────────────────────────────────────────────────────
    "tenerife":           "Tenerife",
    "santa cruz de tenerife": "Tenerife",
    "puerto de la cruz":  "Puerto_de_la_Cruz",
    "los cristianos":     "Los_Cristianos",
    "playa de las americas": "Playa_de_las_Americas",
    "costa adeje":        "Costa_Adeje",
    "el teide":           "Teide",
    "teide":              "Teide",
    "la laguna":          "La_Laguna",
    "gran canaria":       "Gran_Canaria",
    "las palmas":         "Las_Palmas",
    "maspalomas":         "Maspalomas",
    "playa del ingles":   "Playa_del_Ingles",
    "playa del inglés":   "Playa_del_Ingles",
    "mogán":              "Mogan",
    "mogan":              "Mogan",
    "agaete":             "Agaete",
    "fuerteventura":      "Fuerteventura",
    "corralejo":          "Corralejo",
    "jandia":             "Jandia",
    "jandía":             "Jandia",
    "costa calma":        "Costa_Calma",
    "lanzarote":          "Lanzarote",
    "arrecife":           "Arrecife",
    "timanfaya":          "Timanfaya",
    "playa blanca":       "Playa_Blanca",
    "puerto del carmen":  "Puerto_del_Carmen",
    "la palma":           "La_Palma",
    "santa cruz de la palma": "La_Palma",
    "la gomera":          "La_Gomera",
    "el hierro":          "El_Hierro",
    "la graciosa":        "La_Graciosa",

    # ════════════════════════════════════════════════════════════════════════
    # PORTUGAL
    # ════════════════════════════════════════════════════════════════════════
    "lisboa":             "Lisboa",
    "lisbon":             "Lisboa",
    "porto":              "Porto",
    "oporto":             "Porto",
    "faro":               "Faro",
    "albufeira":          "Albufeira",
    "lagos":              "Lagos",
    "portimao":           "Portimao",
    "portimão":           "Portimao",
    "sagres":             "Sagres",
    "vilamoura":          "Vilamoura",
    "quarteira":          "Quarteira",
    "tavira":             "Tavira",
    "olhao":              "Olhao",
    "olhão":              "Olhao",
    "evora":              "Evora",
    "évora":              "Evora",
    "sintra":             "Sintra",
    "cascais":            "Cascais",
    "estoril":            "Estoril",
    "setubal":            "Setubal",
    "setúbal":            "Setubal",
    "coimbra":            "Coimbra",
    "braga":              "Braga",
    "guimaraes":          "Guimaraes",
    "guimarães":          "Guimaraes",
    "viana do castelo":   "Viana_do_Castelo",
    "aveiro":             "Aveiro",
    "viseu":              "Viseu",
    "braganca":           "Braganca",
    "bragança":           "Braganca",
    "obidos":             "Obidos",
    "óbidos":             "Obidos",
    "nazare":             "Nazare",
    "nazaré":             "Nazare",
    "fatima":             "Fatima",
    "fátima":             "Fatima",
    "batalha":            "Batalha",
    "alcobaca":           "Alcobaca",
    "alcobaça":           "Alcobaca",
    "tomar":              "Tomar",
    "monsanto":           "Monsanto",
    "marvao":             "Marvao",
    "marvão":             "Marvao",
    "elvas":              "Elvas",
    "estremoz":           "Estremoz",
    "comporta":           "Comporta",
    "sesimbra":           "Sesimbra",
    "peniche":            "Peniche",
    "ericeira":           "Ericeira",
    "madeira":            "Madeira",
    "funchal":            "Funchal",
    "azores":             "Azores",
    "açores":             "Azores",
    "ponta delgada":      "Ponta_Delgada",

    # ════════════════════════════════════════════════════════════════════════
    # FRANCIA
    # ════════════════════════════════════════════════════════════════════════
    "paris":              "Paris",
    "niza":               "Niza",
    "nice":               "Niza",
    "marsella":           "Marsella",
    "marseille":          "Marsella",
    "lyon":               "Lyon",
    "burdeos":            "Burdeos",
    "bordeaux":           "Burdeos",
    "toulouse":           "Toulouse",
    "nantes":             "Nantes",
    "estrasburgo":        "Estrasburgo",
    "strasbourg":         "Estrasburgo",
    "lille":              "Lille",
    "montpellier":        "Montpellier",
    "cannes":             "Cannes",
    "monaco":             "Monaco",
    "mónaco":             "Monaco",
    "antibes":            "Antibes",
    "saint tropez":       "Saint_Tropez",
    "st tropez":          "Saint_Tropez",
    "carcassonne":        "Carcassonne",
    "avignon":            "Avignon",
    "aix en provence":    "Aix_en_Provence",
    "grenoble":           "Grenoble",
    "annecy":             "Annecy",
    "chamonix":           "Chamonix",
    "mont blanc":         "Mont_Blanc",
    "versalles":          "Versalles",
    "versailles":         "Versalles",
    "mont saint michel":  "Mont_Saint_Michel",
    "normandia":          "Normandia",
    "normandie":          "Normandia",
    "bretaña":            "Bretana",
    "bretagne":           "Bretana",
    "corsica":            "Corsica",
    "córcega":            "Corsica",
    "alsacia":            "Alsacia",
    "alsace":             "Alsacia",
    "bayona":             "Bayonne",
    "bayonne":            "Bayonne",
    "lourdes":            "Lourdes",
    "pau":                "Pau",
    "perpignan":          "Perpignan",
    "colmar":             "Colmar",
    "reims":              "Reims",
    "tours":              "Tours",
    "orleans":            "Orleans",
    "orléans":            "Orleans",
    "rennes":             "Rennes",
    "brest":              "Brest",
    "saint malo":         "Saint_Malo",
    "dijon":              "Dijon",
    "metz":               "Metz",
    "nancy":              "Nancy",
    "clermont ferrand":   "Clermont_Ferrand",
    "la rochelle":        "La_Rochelle",
    "rouen":              "Rouen",
    "caen":               "Caen",
    "calais":             "Calais",
    "dunkerque":          "Dunkerque",

    # ════════════════════════════════════════════════════════════════════════
    # ITALIA
    # ════════════════════════════════════════════════════════════════════════
    "roma":               "Roma",
    "rome":               "Roma",
    "milan":              "Milan",
    "milán":              "Milan",
    "milano":             "Milan",
    "venecia":            "Venecia",
    "venice":             "Venecia",
    "venezia":            "Venecia",
    "florencia":          "Florencia",
    "florence":           "Florencia",
    "firenze":            "Florencia",
    "napoles":            "Napoles",
    "nápoles":            "Napoles",
    "napoli":             "Napoles",
    "turin":              "Turin",
    "turín":              "Turin",
    "torino":             "Turin",
    "bolonia":            "Bolonia",
    "bologna":            "Bolonia",
    "genova":             "Genova",
    "génova":             "Genova",
    "pisa":               "Pisa",
    "siena":              "Siena",
    "amalfi":             "Amalfi",
    "positano":           "Positano",
    "capri":              "Capri",
    "pompeya":            "Pompeya",
    "pompeii":            "Pompeya",
    "pompei":             "Pompeya",
    "sorrento":           "Sorrento",
    "ravena":             "Ravena",
    "ravenna":            "Ravena",
    "verona":             "Verona",
    "padova":             "Padova",
    "padua":              "Padova",
    "trieste":            "Trieste",
    "perugia":            "Perugia",
    "asís":               "Asis",
    "asis":               "Asis",
    "assisi":             "Asis",
    "orvieto":            "Orvieto",
    "palermo":            "Palermo",
    "sicilia":            "Sicilia",
    "sicily":             "Sicilia",
    "catania":            "Catania",
    "siracusa":           "Siracusa",
    "cerdeña":            "Cerdeña",
    "sardinia":           "Cerdeña",
    "sardegna":           "Cerdeña",
    "cagliari":           "Cagliari",
    "olbia":              "Olbia",
    "costa esmeralda":    "Costa_Esmeralda",
    "lago di como":       "Como",
    "como":               "Como",
    "lago maggiore":      "Lago_Maggiore",
    "stresa":             "Stresa",
    "lago di garda":      "Lago_di_Garda",
    "sirmione":           "Sirmione",
    "riva del garda":     "Riva_del_Garda",
    "cortina":            "Cortina_dAmpezzo",
    "dolomitas":          "Dolomitas",
    "dolomiti":           "Dolomitas",
    "cinque terre":       "Cinque_Terre",
    "portofino":          "Portofino",
    "lucca":              "Lucca",
    "san gimignano":      "San_Gimignano",
    "volterra":           "Volterra",
    "montepulciano":      "Montepulciano",
    "pienza":             "Pienza",
    "val d'orcia":        "Val_dOrcia",
    "toscana":            "Toscana",
    "umbria":             "Umbria",
    "umbría":             "Umbria",
    "matera":             "Matera",
    "alberobello":        "Alberobello",
    "lecce":              "Lecce",
    "bari":               "Bari",
    "brindisi":           "Brindisi",
    "taormina":           "Taormina",
    "etna":               "Etna",
    "agrigento":          "Agrigento",
    "trapani":            "Trapani",
    "ragusa":             "Ragusa",
    "modica":             "Modica",
    "noto":               "Noto",

    # ════════════════════════════════════════════════════════════════════════
    # ALEMANIA
    # ════════════════════════════════════════════════════════════════════════
    "berlin":             "Berlin",
    "munich":             "Munich",
    "münchen":            "Munich",
    "munchen":            "Munich",
    "hamburgo":           "Hamburgo",
    "hamburg":            "Hamburgo",
    "colonia":            "Colonia",
    "cologne":            "Colonia",
    "köln":               "Colonia",
    "koln":               "Colonia",
    "frankfurt":          "Frankfurt",
    "frankfurt am main":  "Frankfurt",
    "stuttgart":          "Stuttgart",
    "dusseldorf":         "Dusseldorf",
    "düsseldorf":         "Dusseldorf",
    "dortmund":           "Dortmund",
    "essen":              "Essen",
    "bremen":             "Bremen",
    "hannover":           "Hannover",
    "leipzig":            "Leipzig",
    "dresde":             "Dresden",
    "dresden":            "Dresden",
    "nuremberg":          "Nuremberg",
    "nürnberg":           "Nuremberg",
    "nurnberg":           "Nuremberg",
    "heidelberg":         "Heidelberg",
    "freiburg":           "Freiburg",
    "freiburgo":          "Freiburg",
    "estrasburgo":        "Estrasburgo",
    "rostock":            "Rostock",
    "kiel":               "Kiel",
    "lubeck":             "Lubeck",
    "lübeck":             "Lubeck",
    "augsburg":           "Augsburg",
    "augsburgo":          "Augsburg",
    "regensburg":         "Regensburg",
    "ratisbona":          "Regensburg",
    "wuerzburg":          "Wurzburg",
    "würzburg":           "Wurzburg",
    "bamberg":            "Bamberg",
    "rothenburg":         "Rothenburg",
    "ruta romantica":     "Ruta_Romantica",
    "ruta romántica":     "Ruta_Romantica",
    "romantische strasse":"Ruta_Romantica",
    "neuschwanstein":     "Neuschwanstein",
    "baviera":            "Baviera",
    "bavaria":            "Baviera",
    "selva negra":        "Selva_Negra",
    "schwarzwald":        "Selva_Negra",
    "lago constanza":     "Lago_Constanza",
    "bodensee":           "Lago_Constanza",
    "bonn":               "Bonn",
    "trier":              "Trier",
    "treveris":           "Trier",
    "wiesbaden":          "Wiesbaden",
    "maguncia":           "Maguncia",
    "mainz":              "Maguncia",
    "bingen":             "Bingen",
    "rudesheim":          "Rudesheim",
    "rüdesheim":          "Rudesheim",
    "kassel":             "Kassel",
    "erfurt":             "Erfurt",
    "weimar":             "Weimar",
    "potsdam":            "Potsdam",
    "quedlinburg":        "Quedlinburg",
    "goslar":             "Goslar",
    "wernigerode":        "Wernigerode",

    # ════════════════════════════════════════════════════════════════════════
    # RESTO DE EUROPA (viajes frecuentes)
    # ════════════════════════════════════════════════════════════════════════
    "london":             "Londres",
    "londres":            "Londres",
    "amsterdam":          "Amsterdam",
    "bruselas":           "Bruselas",
    "brussels":           "Bruselas",
    "brujas":             "Brujas",
    "bruges":             "Brujas",
    "gante":              "Gante",
    "ghent":              "Gante",
    "viena":              "Viena",
    "vienna":             "Viena",
    "wien":               "Viena",
    "praga":              "Praga",
    "prague":             "Praga",
    "budapest":           "Budapest",
    "varsovia":           "Varsovia",
    "warsaw":             "Varsovia",
    "cracovia":           "Cracovia",
    "krakow":             "Cracovia",
    "cracow":             "Cracovia",
    "atenas":             "Atenas",
    "athens":             "Atenas",
    "santorini":          "Santorini",
    "mykonos":            "Mykonos",
    "creta":              "Creta",
    "crete":              "Creta",
    "heraklion":          "Heraklion",
    "rodos":              "Rodas",
    "rhodes":             "Rodas",
    "corfu":              "Corfu",
    "corfú":              "Corfu",
    "zakynthos":          "Zakynthos",
    "zante":              "Zakynthos",
    "estocolmo":          "Estocolmo",
    "stockholm":          "Estocolmo",
    "oslo":               "Oslo",
    "copenhague":         "Copenhague",
    "copenhagen":         "Copenhague",
    "helsinki":           "Helsinki",
    "dublin":             "Dublin",
    "dublín":             "Dublin",
    "edimburgo":          "Edimburgo",
    "edinburgh":          "Edimburgo",
    "glasgow":            "Glasgow",
    "zurich":             "Zurich",
    "zúrich":             "Zurich",
    "ginebra":            "Ginebra",
    "geneva":             "Ginebra",
    "berna":              "Berna",
    "bern":               "Berna",
    "lucerna":            "Lucerna",
    "luzern":             "Lucerna",
    "interlaken":         "Interlaken",
    "zermatt":            "Zermatt",
    "zagreb":             "Zagreb",
    "dubrovnik":          "Dubrovnik",
    "split":              "Split",
    "hvar":               "Hvar",
    "kotor":              "Kotor",
    "liubliana":          "Liubliana",
    "ljubljana":          "Liubliana",
    "bratislava":         "Bratislava",
    "oporto":             "Porto",
    "tallinn":            "Tallinn",
    "riga":               "Riga",
    "vilnius":            "Vilnius",
    "bucarest":           "Bucarest",
    "bucharest":          "Bucarest",
    "belgrado":           "Belgrado",
    "belgrade":           "Belgrado",
    "sarajevo":           "Sarajevo",
    "sofia":              "Sofia",
    "reykjavik":          "Reykjavik",
    "islandia":           "Islandia",
    "iceland":            "Islandia",
    "malta":              "Malta",
    "la valeta":          "Malta",
    "valletta":           "Malta",
    "chipre":             "Chipre",
    "cyprus":             "Chipre",
    "nicosia":            "Nicosia",
    "palma de mallorca":  "Mallorca",

    # ════════════════════════════════════════════════════════════════════════
    # RESTO DEL MUNDO
    # ════════════════════════════════════════════════════════════════════════
    "new york":           "Nueva_York",
    "nueva york":         "Nueva_York",
    "newyork":            "Nueva_York",
    "miami":              "Miami",
    "los angeles":        "Los_Angeles",
    "san francisco":      "San_Francisco",
    "chicago":            "Chicago",
    "las vegas":          "Las_Vegas",
    "orlando":            "Orlando",
    "washington":         "Washington",
    "boston":             "Boston",
    "seattle":            "Seattle",
    "toronto":            "Toronto",
    "montreal":           "Montreal",
    "vancouver":          "Vancouver",
    "cancun":             "Cancun",
    "cancún":             "Cancun",
    "mexico":             "Mexico",
    "ciudad de mexico":   "Ciudad_de_Mexico",
    "guadalajara mx":     "Guadalajara_Mexico",
    "cuba":               "Cuba",
    "la habana":          "La_Habana",
    "havana":             "La_Habana",
    "republica dominicana": "Rep_Dominicana",
    "punta cana":         "Punta_Cana",
    "santo domingo":      "Santo_Domingo",
    "jamaica":            "Jamaica",
    "costa rica":         "Costa_Rica",
    "peru":               "Peru",
    "perú":               "Peru",
    "machu picchu":       "Machu_Picchu",
    "lima":               "Lima",
    "cuzco":              "Cuzco",
    "cusco":              "Cuzco",
    "argentina":          "Argentina",
    "buenos aires":       "Buenos_Aires",
    "patagonia":          "Patagonia",
    "chile":              "Chile",
    "santiago de chile":  "Santiago_de_Chile",
    "brasil":             "Brasil",
    "rio de janeiro":     "Rio_de_Janeiro",
    "rio":                "Rio_de_Janeiro",
    "sao paulo":          "Sao_Paulo",
    "dubai":              "Dubai",
    "abu dhabi":          "Abu_Dhabi",
    "qatar":              "Qatar",
    "doha":               "Doha",
    "jordania":           "Jordania",
    "petra":              "Petra",
    "israel":             "Israel",
    "jerusalem":          "Jerusalem",
    "tel aviv":           "Tel_Aviv",
    "turquia":            "Turquia",
    "turkey":             "Turquia",
    "estambul":           "Estambul",
    "istanbul":           "Estambul",
    "capadocia":          "Capadocia",
    "cappadocia":         "Capadocia",
    "egipto":             "Egipto",
    "egypt":              "Egipto",
    "cairo":              "El_Cairo",
    "luxor":              "Luxor",
    "aswan":              "Aswan",
    "hurghada":           "Hurghada",
    "sharm el sheikh":    "Sharm_el_Sheikh",
    "marrakech":          "Marrakech",
    "marruecos":          "Marruecos",
    "morocco":            "Marruecos",
    "fez":                "Fez",
    "fes":                "Fez",
    "casablanca":         "Casablanca",
    "tanger":             "Tanger",
    "tánger":             "Tanger",
    "tailandia":          "Tailandia",
    "thailand":           "Tailandia",
    "bangkok":            "Bangkok",
    "phuket":             "Phuket",
    "chiang mai":         "Chiang_Mai",
    "koh samui":          "Koh_Samui",
    "bali":               "Bali",
    "indonesia":          "Indonesia",
    "japon":              "Japon",
    "japón":              "Japon",
    "japan":              "Japon",
    "tokyo":              "Tokyo",
    "tokio":              "Tokyo",
    "kyoto":              "Kyoto",
    "osaka":              "Osaka",
    "hiroshima":          "Hiroshima",
    "china":              "China",
    "beijing":            "Beijing",
    "pekin":              "Beijing",
    "pekín":              "Beijing",
    "shanghai":           "Shanghai",
    "india":              "India",
    "delhi":              "Delhi",
    "mumbai":             "Mumbai",
    "bombay":             "Mumbai",
    "agra":               "Agra",
    "taj mahal":          "Taj_Mahal",
    "rajasthan":          "Rajasthan",
    "jaipur":             "Jaipur",
    "vietnam":            "Vietnam",
    "hanoi":              "Hanoi",
    "ho chi minh":        "Ho_Chi_Minh",
    "saigon":             "Ho_Chi_Minh",
    "hoi an":             "Hoi_An",
    "ha long":            "Ha_Long",
    "singapur":           "Singapur",
    "singapore":          "Singapur",
    "australia":          "Australia",
    "sydney":             "Sydney",
    "melbourne":          "Melbourne",
    "brisbane":           "Brisbane",
    "nueva zelanda":      "Nueva_Zelanda",
    "new zealand":        "Nueva_Zelanda",
    "auckland":           "Auckland",
    "sudafrica":          "Sudafrica",
    "sudáfrica":          "Sudafrica",
    "south africa":       "Sudafrica",
    "ciudad del cabo":    "Ciudad_del_Cabo",
    "cape town":          "Ciudad_del_Cabo",
    "safari":             "Safari",
    "kenia":              "Kenia",
    "kenya":              "Kenia",
    "nairobi":            "Nairobi",
    "tanzania":           "Tanzania",
    "serengeti":          "Serengeti",
    "zanzibar":           "Zanzibar",
    "zanzíbar":           "Zanzibar",
}
    "amsterdam":  "Amsterdam",
    "berlin":     "Berlin",
    "lisboa":     "Lisboa",
    "lisbon":     "Lisboa",
    "tokyo":      "Tokyo",
    "tokio":      "Tokyo",
    "dubai":      "Dubai",
    "mexico":     "Mexico",
    "cancun":     "Cancun",
    "miami":      "Miami",
    "venice":     "Venecia",
    "venecia":    "Venecia",
    "florencia":  "Florencia",
    "florence":   "Florencia",
    "prague":     "Praga",
    "praga":      "Praga",
    "vienna":     "Viena",
    "viena":      "Viena",
    "budapest":   "Budapest",
    "athens":     "Atenas",
    "atenas":     "Atenas",
    "cairo":      "El_Cairo",
    "marrakech":  "Marrakech",
    "bangkok":    "Bangkok",
    "bali":       "Bali",
    "sydney":     "Sydney",
    "toronto":    "Toronto",
    "chicago":    "Chicago",
    # ── Islas españolas ──────────────────────────────────────────────────────
    "tenerife":       "Tenerife",
    "gran canaria":   "Gran_Canaria",
    "fuerteventura":  "Fuerteventura",
    "lanzarote":      "Lanzarote",
    "la palma":       "La_Palma",
    "la gomera":      "La_Gomera",
    "el hierro":      "El_Hierro",
    "mallorca":       "Mallorca",
    "palma":          "Mallorca",
    "menorca":        "Menorca",
    "ibiza":          "Ibiza",
    "formentera":     "Formentera",
    # ── País Vasco ───────────────────────────────────────────────────────────
    "donostia":       "Donostia",
    "san sebastian":  "Donostia",
    "san sebastián":  "Donostia",
    "bilbao":         "Bilbao",
    "vitoria":        "Vitoria",
    "gasteiz":        "Vitoria",
    "hondarribia":    "Hondarribia",
    "zarautz":        "Zarautz",
    "getaria":        "Getaria",
    "zumaia":         "Zumaia",
    "mutriku":        "Mutriku",
    "lekeitio":       "Lekeitio",
    "bermeo":         "Bermeo",
    "guernica":       "Guernica",
    "gernika":        "Guernica",
    "mundaka":        "Mundaka",
    "ondarroa":       "Ondarroa",
    "elgoibar":       "Elgoibar",
    "eibar":          "Eibar",
    "arrasate":       "Mondragon",
    "mondragon":      "Mondragon",
    "beasain":        "Beasain",
    "tolosa":         "Tolosa",
    "azpeitia":       "Azpeitia",
    "zumarraga":      "Zumarraga",
    "irun":           "Irun",
    "renteria":       "Renteria",
    "errenteria":     "Renteria",
    "pasajes":        "Pasajes",
    "pasaia":         "Pasajes",
    "andoain":        "Andoain",
    "hernani":        "Hernani",
    "biarritz":       "Biarritz",
    # ── Navarra / La Rioja ───────────────────────────────────────────────────
    "pamplona":       "Pamplona",
    "iruña":          "Pamplona",
    "logrono":        "Logrono",
    "logroño":        "Logrono",
    "estella":        "Estella",
    "tudela":         "Tudela",
    # ── Aragón ───────────────────────────────────────────────────────────────
    "zaragoza":       "Zaragoza",
    "huesca":         "Huesca",
    "teruel":         "Teruel",
    "jaca":           "Jaca",
    "benasque":       "Benasque",
    "ordesa":         "Ordesa",
    # ── Cataluña ─────────────────────────────────────────────────────────────
    "barcelona":      "Barcelona",
    "girona":         "Girona",
    "gerona":         "Girona",
    "tarragona":      "Tarragona",
    "lleida":         "Lleida",
    "lerida":         "Lleida",
    "sitges":         "Sitges",
    "costa brava":    "Costa_Brava",
    "cadaques":       "Cadaques",
    "cadaqués":       "Cadaques",
    "figueres":       "Figueres",
    "vic":            "Vic",
    "manresa":        "Manresa",
    "montserrat":     "Montserrat",
    # ── Comunidad Valenciana ─────────────────────────────────────────────────
    "valencia":       "Valencia",
    "alicante":       "Alicante",
    "benidorm":       "Benidorm",
    "denia":          "Denia",
    "javea":          "Javea",
    "jávea":          "Javea",
    "calpe":          "Calpe",
    "altea":          "Altea",
    "gandia":         "Gandia",
    "castellon":      "Castellon",
    "castellón":      "Castellon",
    "peniscola":      "Peniscola",
    "peñíscola":      "Peniscola",
    # ── Andalucía ────────────────────────────────────────────────────────────
    "sevilla":        "Sevilla",
    "granada":        "Granada",
    "malaga":         "Malaga",
    "málaga":         "Malaga",
    "cordoba":        "Cordoba",
    "córdoba":        "Cordoba",
    "cadiz":          "Cadiz",
    "cádiz":          "Cadiz",
    "huelva":         "Huelva",
    "almeria":        "Almeria",
    "almería":        "Almeria",
    "jaen":           "Jaen",
    "jaén":           "Jaen",
    "marbella":       "Marbella",
    "torremolinos":   "Torremolinos",
    "nerja":          "Nerja",
    "ronda":          "Ronda",
    "jerez":          "Jerez",
    "tarifa":         "Tarifa",
    "gibraltar":      "Gibraltar",
    # ── Castilla ─────────────────────────────────────────────────────────────
    "madrid":         "Madrid",
    "toledo":         "Toledo",
    "segovia":        "Segovia",
    "avila":          "Avila",
    "ávila":          "Avila",
    "salamanca":      "Salamanca",
    "valladolid":     "Valladolid",
    "burgos":         "Burgos",
    "leon":           "Leon",
    "león":           "Leon",
    "zamora":         "Zamora",
    "palencia":       "Palencia",
    "soria":          "Soria",
    "guadalajara":    "Guadalajara",
    "cuenca":         "Cuenca",
    "ciudad real":    "Ciudad_Real",
    "albacete":       "Albacete",
    # ── Galicia ──────────────────────────────────────────────────────────────
    "santiago":       "Santiago_de_Compostela",
    "compostela":     "Santiago_de_Compostela",
    "vigo":           "Vigo",
    "coruña":         "A_Coruna",
    "a coruña":       "A_Coruna",
    "pontevedra":     "Pontevedra",
    "ourense":        "Ourense",
    "lugo":           "Lugo",
    "rias bajas":     "Rias_Bajas",
    # ── Asturias / Cantabria ─────────────────────────────────────────────────
    "oviedo":         "Oviedo",
    "gijon":          "Gijon",
    "gijón":          "Gijon",
    "aviles":         "Aviles",
    "avilés":         "Aviles",
    "santander":      "Santander",
    "comillas":       "Comillas",
    "san vicente":    "San_Vicente_Barquera",
    "picos de europa":"Picos_de_Europa",
    "covadonga":      "Covadonga",
    # ── Extremadura / Murcia ─────────────────────────────────────────────────
    "caceres":        "Caceres",
    "cáceres":        "Caceres",
    "badajoz":        "Badajoz",
    "merida":         "Merida",
    "mérida":         "Merida",
    "murcia":         "Murcia",
    "cartagena":      "Cartagena",
    # ── Resto ciudades España ────────────────────────────────────────────────
    "elche":          "Elche",
    "elx":            "Elche",
    "alcala":         "Alcala_de_Henares",
    "aranjuez":       "Aranjuez",
    "el escorial":    "El_Escorial",
}


def city_from_folder_name(folder_name: str) -> Optional[str]:
    """Detecta una ciudad conocida en el nombre de la carpeta."""
    lower = folder_name.lower()
    for keyword, city in FOLDER_CITY_KEYWORDS.items():
        if keyword in lower:
            return city
    return None
